export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS";
export const PRODUCTS_REQUEST_FAIL = "PRODUCTS_REQUEST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";
